version: "3.7"
services:
  #application
  app:
    build:
      args:
        user: maruan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: main_application
    restart: always
    working_dir: /var/www/
    volumes:
      - ./app/:/var/www
    networks:
      - network

 #Nginx Service
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
        # - ./nginx/log/:/var/log/nginx/error.log
        # - ./nginx/log/:/var/log/nginx/access.log
    networks:
      - network

  #Mysql Service
  db:
    image: mysql:8
    restart: always
    volumes:
      - ./database/data/:/var/lib/mysql
      - ./database/logs/:/var/log/mysql
    environment:
      MYSQL_DATABASE: 'dbname'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
      MYSQL_USER: 'sa'
    networks:
      - network

  #phpmyadmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    networks:
      - network
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80

networks:
  network:
    driver: bridge
